# .github/workflows/qiita.yml
name: "GitHub to Qiita"

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  qiita:
    runs-on: ubuntu-latest
    steps:
      - name: "Publish qiita article"
        uses: mitchel2003/mern_crud@v1.0.0
        with:
          # dir: "articles"
          qiita_access_token: ${{ secrets.QIITA_ACCESS_TOKEN }}
          mapping_filepath: "mapping.txt"
          strict: false