# .github/workflows/publish.yml
name: "GitHub to Qiita"

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  qiita:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout del repositorio
      uses: actions/checkout@v4

    - name: Publicar en Qiita
      uses: increments/qiita-cli/actions/publish@v1
      with:
        qiita_access_token: ${{ secrets.QIITA_ACCESS_TOKEN }}
        mapping_filepath: "mapping.txt"
        strict: false
        root: "."