# Please set 'QIITA_TOKEN' secret to your repository
name: Publish articles

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  publish_articles:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Check if secret is available
        run: |
          echo "::add-mask::${QIITA_TOKEN}"
          echo "Token length: $(echo -n "${QIITA_TOKEN}" | wc -c)"
        env:
          QIITA_TOKEN: ${{ secrets.QIITA_TOKEN }}

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Publish to Qiita
        uses: increments/qiita-cli/actions/publish@v1
        with:
          qiita_token: ${{ secrets.QIITA_TOKEN }}
          root: "."