# .github/workflows/publish.yml
name: "GitHub to Qiita"

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  qiita:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Config credentials
      run: |
        mkdir -p ~/.config/qiita-cli
        echo '{"qiita_access_token": "${{ secrets.QIITA_ACCESS_TOKEN }}"}' > ~/.config/qiita-cli/credentials.json

    - name: Publish
      uses: increments/qiita-cli/actions/publish@v1
      with:
        qiita-token: ${{ secrets.QIITA_ACCESS_TOKEN }}
        root: "."